# -*- coding: utf-8 -*-
"""week4_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJbrizH8D5_ox1KelY_CpF2GGmPTSST9
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt
import pickle

candidates = {'SAT': [1560,1500,1380,1420,1360,1460,1380,1440,1480,1380,1220,1380,1420,1360,1540,1220,1160,1300,1080,1180,1240,1200,1100,1100,1140,1340,1320,1160,1300,1320,1280,1240,1320,1320,1360,1300,1340,1160,1180,1380],
              'GPA': [3.9,3.8,3.2,3.6,4.0,3.6,2.2,3.4,3.3,1.7,2.7,3.7,3.7,3.3,3.3,3,2.7,3.7,2.7,2.3,3.3,2,2.3,2.7,3,3.3,3.7,2.3,3.7,3.3,3,2.7,4,3.3,3.3,2.3,2.7,3.3,1.7,3.7],
              'Experience': [3,4,3,5,4,6,1,5,4,3,3,5,6,4,3,1,4,6,2,3,2,2,3,1,2,5,2,5,6,2,2,3,6,4,1,3,1,5,5,5],
              'Accepted': [1,1,0,1,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,1]
              }

df = pd.DataFrame(candidates,columns= ['SAT', 'GPA','Experience','Accepted'])

df.head(5)

df.isnull().sum().sum()

X = df[['SAT','GPA','Experience']]
y = df['Accepted']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

logistic_regression= LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_pred=logistic_regression.predict(X_test)
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))

filename = 'model_.pkl'
pickle.dump(logistic_regression, open(filename, 'wb'))

filename = 'model_.pkl'
model = pickle.load(open(filename, 'rb'))
result =model.score(X_test, y_test)
print(result)

new_df= {'SAT':[1600,400,450], 'GPA':[2.5,2.1,3.5], 'Experience':[2,2,2] }

new_df = pd.DataFrame(new_df,columns= ['SAT','GPA' ,'Experience'])
y_pred=model.predict(new_df)

print (new_df)
print (y_pred)